const cards = [
  {
    id: 1,
    image: "./assets/items/round_one/Raspberry-Icon.png",
    imageFull: "./assets/items/round_one/Raspberry-Icon-Large.png",
    name: "Raspberry",
    description: "A classic raspberry.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-06-25",
    discontinuedDate: "2024-07-06",
    status: "discontinued",
  },
  {
    id: 2,
    image: "./assets/items/round_one/Raspberry-Smiles-Icon.png",
    imageFull: "./assets/items/round_one/Raspberry-Smiles-Icon-Large.png",
    name: "Smileberry",
    description: "Sometimes raspberries smile back.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-06-25",
    discontinuedDate: "2024-07-06",
    status: "discontinued",
  },
  {
    id: 3,
    image: "./assets/items/round_one/Raspberry-CommunityBeta-Icon.png",
    imageFull:
      "./assets/items/round_one/Raspberry-CommunityBeta-Icon-Large.png",
    name: "Betaberry",
    description: "For those who like to live on the edge.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-06-25",
    discontinuedDate: "2024-07-05",
    status: "discontinued",
  },
  {
    id: 4,
    image: "./assets/items/round_one/Raspberry-Soldier-Icon.png",
    imageFull: "./assets/items/round_one/Raspberry-Soldier-Icon-Large.png",
    name: "Soldierberry",
    description: "A raspberry ready for battle.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-06-25",
    discontinuedDate: "2024-07-18",
    status: "discontinued",
  },
  {
    id: 5,
    image: "./assets/items/round_one/Raspberry-Baby-Icon.png",
    imageFull: "./assets/items/round_one/Raspberry-Baby-Icon-Large.png",
    name: "Babyberry",
    description: "Aww, it's a baby raspberry!",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-06-25",
    discontinuedDate: "2024-07-18",
    status: "discontinued",
  },
  {
    id: 6,
    image: "./assets/items/round_one/Raspberry-Ninja-Icon.png",
    imageFull: "./assets/items/round_one/Raspberry-Ninja-Icon-Large.png",
    name: "Ninjaberry",
    description: "A raspberry that strikes from the shadows.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-06-25",
    status: "live",
  },
  {
    id: 7,
    image: "./assets/items/round_two/Raspberry-Pixel-Icon.png",
    imageFull: "./assets/items/round_two/Raspberry-Pixel-Icon-Large.png",
    name: "Pixelberry",
    description: "A raspberry from the past.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-03",
    discontinuedDate: "2024-07-06",
    status: "discontinued",
  },
  {
    id: 8,
    image: "./assets/items/round_two/Raspberry-Shine-Icon.png",
    imageFull: "./assets/items/round_two/Raspberry-Shine-Icon-Large.png",
    name: "Shineberry",
    description: "A raspberry that sparkles.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-03",
    discontinuedDate: "2024-07-06",
    status: "discontinued",
  },
  {
    id: 9,
    image: "./assets/items/round_two/Raspberry-Noir-Icon.png",
    imageFull: "./assets/items/round_two/Raspberry-Noir-Icon-Large.png",
    name: "Noirberry",
    description: "A raspberry with a mysterious past.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-03",
    discontinuedDate: "2024-07-18",
    status: "discontinued",
  },
  {
    id: 10,
    image: "./assets/items/round_two/Raspberry-Space-Icon.png",
    imageFull: "./assets/items/round_two/Raspberry-Space-Icon-Large.png",
    name: "Spaceberry",
    description: "A raspberry from the stars.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-03",
    discontinuedDate: "2024-07-07",
    status: "discontinued",
  },
  {
    id: 11,
    image: "./assets/items/event/july/Raspberry-July4th-Icon.png",
    imageFull: "./assets/items/event/july/Raspberry-July4th-Icon-Large.png",
    name: "Freedomberry",
    description: "A raspberry bursting with patriotism.",
    rarity: "event",
    value: 0.25,
    dateAdded: "2024-07-04",
    discontinuedDate: "2024-07-04",
    status: "discontinued",
  },
  {
    id: 12,
    image: "./assets/items/round_three/Raspberry-Eye-Icon.png",
    imageFull: "./assets/items/round_three/Raspberry-Eye-Icon-Large.png",
    name: "Eyeberry",
    description: "A raspberry bursting thats always watching.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-04",
    status: "live",
  },
  {
    id: 13,
    image: "./assets/items/round_three/Raspberry-Pepe-Icon.png",
    imageFull: "./assets/items/round_three/Raspberry-Pepe-Icon-Large.png",
    name: "Pepeberry",
    description: "A raspberry that's a little bit of a meme.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-04",
    status: "live",
  },
  {
    id: 14,
    image: "./assets/items/round_three/Raspberry-Tarot-Icon.png",
    imageFull: "./assets/items/round_three/Raspberry-Tarot-Icon-Large.png",
    name: "Tarotberry",
    description: "A raspberry infused with the essence of tarot.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-04",
    discontinuedDate: "2024-07-06",
    status: "discontinued",
  },
  {
    id: 15,
    image: "./assets/items/round_four/Raspberry-Juicy-Icon.png",
    imageFull: "./assets/items/round_four/Raspberry-Juicy-Icon-Large.png",
    name: "Juicyberry",
    description: "A raspberry that's extra juicy.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-05",
    discontinuedDate: "2024-07-08",
    status: "discontinued",
  },
  {
    id: 16,
    image: "./assets/items/round_four/Raspberry-Moon-Icon.png",
    imageFull: "./assets/items/round_four/Raspberry-Moon-Icon-Large.png",
    name: "Moonberry",
    description: "A raspberry that's out of this world.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-05",
    status: "live",
  },
  {
    id: 17,
    image: "./assets/items/round_four/Raspberry-Poncho-Icon.png",
    imageFull: "./assets/items/round_four/Raspberry-Poncho-Icon-Large.png",
    name: "Ponchoberry",
    description: "A raspberry that's part cat.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-05",
    status: "live",
  },
  {
    id: 18,
    image: "./assets/items/round_five/Raspberry-EAC-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-EAC-Icon-Large.png",
    name: "Anticheatberry",
    description: "A raspberry that's always watching.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 19,
    image: "./assets/items/round_five/Raspberry-Bubble-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Bubble-Icon-Large.png",
    name: "Bubbleberry",
    description: "Breathe out, breathe in...",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 20,
    image: "./assets/items/round_five/Raspberry-Burning-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Burning-Icon-Large.png",
    name: "Burningberry",
    description: "Sometimes raspberries are on fire.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 21,
    image: "./assets/items/round_five/Raspberry-Murder-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Murder-Icon-Large.png",
    name: "Murderberry",
    description: "Who the hell dares?",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 22,
    image: "./assets/items/round_five/Raspberry-Riot-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Riot-Icon-Large.png",
    name: "Riotberry",
    description: "Nostalgia for a time you never lived in.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 23,
    image: "./assets/items/round_five/Raspberry-Cthulhu-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Cthulhu-Icon-Large.png",
    name: "Cthulhuberry",
    description: "From the depths of R'lyeh",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 24,
    image: "./assets/items/round_five/Raspberry-Voodoo-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Voodoo-Icon-Large.png",
    name: "Voodooberry",
    description: "A raspberry that's a little bit cursed.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 25,
    image: "./assets/items/round_five/Raspberry-CD-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-CD-Icon-Large.png",
    name: "BerryFM",
    description: "Your latest selection of clicker music",
    rarity: "buyable",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 26,
    image: "./assets/items/round_five/Raspberry-Snowglobe-Icon.png",
    imageFull: "./assets/items/round_five/Raspberry-Snowglobe-Icon-Large.png",
    name: "Irrationalberry",
    description: "It's Refreshing! Just what you need this hot summer.",
    rarity: "buyable",
    value: 0.25,
    dateAdded: "2024-07-06",
    status: "live",
  },
  {
    id: 27,
    image: "./assets/items/round_six/Raspberry-Blue-Icon.png",
    imageFull: "./assets/items/round_six/Raspberry-Blue-Icon-Large.png",
    name: "Blueberry",
    description: "A raspberry that's a little bit blue.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-07",
    status: "live",
  },
  {
    id: 28,
    image: "./assets/items/round_six/Raspberry-Devil-Icon.png",
    imageFull: "./assets/items/round_six/Raspberry-Devil-Icon-Large.png",
    name: "Devilberry",
    description: "A raspberry that's a little bit evil.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-07",
    status: "live",
  },
  {
    id: 29,
    image: "./assets/items/round_six/Raspberry-Dimascus-Icon.png",
    imageFull: "./assets/items/round_six/Raspberry-Dimascus-Icon-Large.png",
    name: "Dimascusberry",
    description: "A raspberry that's a little bit sharp.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-07",
    status: "live",
  },
  {
    id: 30,
    image: "./assets/items/round_six/Raspberry-Real-Icon.png",
    imageFull: "./assets/items/round_six/Raspberry-Real-Icon-Large.png",
    name: "Realberry",
    description: "A raspberry that's a real.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-07",
    status: "live",
  },
  {
    id: 31,
    image: "./assets/items/round_six/Raspberry-Transparent-Icon.png",
    imageFull: "./assets/items/round_six/Raspberry-Transparent-Icon-Large.png",
    name: "Transparentberry",
    description: "A raspberry that's see-through.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-07",
    status: "live",
  },

  {
    id: 32,
    image: "./assets/items/round_seven/Raspberry-JewelBerry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-JewelBerry-Icon-Large.png",
    name: "Jewelberry",
    description: "A raspberry that sparkles like a jewel.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 33,
    image: "./assets/items/round_seven/Raspberry-Amethystberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Amethystberry-Icon-Large.png",
    name: "Amethystberry",
    description: "A raspberry infused with the power of amethyst.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 34,
    image: "./assets/items/round_seven/Raspberry-Eclipse-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-Eclipse-Icon-Large.png",
    name: "Eclipseberry",
    description: "A raspberry shadowed by an eclipse.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 35,
    image: "./assets/items/round_seven/Raspberry-Emeraldberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Emeraldberry-Icon-Large.png",
    name: "Emeraldberry",
    description: "A raspberry gleaming with emerald light.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 36,
    image: "./assets/items/round_seven/Raspberry-Frozenberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Frozenberry-Icon-Large.png",
    name: "Frozenberry",
    description: "A raspberry frozen in time.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 37,
    image: "./assets/items/round_seven/Raspberry-Happyberry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-Happyberry-Icon-Large.png",
    name: "Happyberry",
    description: "A raspberry that brings joy to all.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 38,
    image: "./assets/items/round_seven/Raspberry-Lowpolyberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Lowpolyberry-Icon-Large.png",
    name: "Lowpolyberry",
    description: "A raspberry with a geometric charm.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 39,
    image: "./assets/items/round_seven/Raspberry-Pinkberry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-Pinkberry-Icon-Large.png",
    name: "Pinkberry",
    description: "A raspberry with a rosy hue.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 40,
    image: "./assets/items/round_seven/Raspberry-Rainbowberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Rainbowberry-Icon-Large.png",
    name: "Rainbowberry",
    description: "A raspberry that reflects the colors of the rainbow.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 41,
    image: "./assets/items/round_seven/Raspberry-RaspberryEXE-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-RaspberryEXE-Icon-Large.png",
    name: "RaspberryEXE",
    description: "A raspberry with a digital twist.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 42,
    image: "./assets/items/round_seven/Raspberry-Retroberry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-Retroberry-Icon-Large.png",
    name: "Retroberry",
    description: "A raspberry with a nostalgic flavor.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 43,
    image: "./assets/items/round_seven/Raspberry-Starberry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-Starberry-Icon-Large.png",
    name: "Starberry",
    description: "A raspberry that shines bright like a star.",
    rarity: "legendary",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 44,
    image: "./assets/items/round_seven/Raspberry-Sunriseberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Sunriseberry-Icon-Large.png",
    name: "Sunriseberry",
    description: "A raspberry glowing with the colors of dawn.",
    rarity: "rare",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 45,
    image: "./assets/items/round_seven/Raspberry-UFOberry-Icon.png",
    imageFull: "./assets/items/round_seven/Raspberry-UFOberry-Icon-Large.png",
    name: "UFOberry",
    description: "A raspberry from another world.",
    rarity: "buyable",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
  {
    id: 46,
    image: "./assets/items/round_seven/Raspberry-Vegetableberry-Icon.png",
    imageFull:
      "./assets/items/round_seven/Raspberry-Vegetableberry-Icon-Large.png",
    name: "Vegetableberry",
    description: "A raspberry that's a little bit of a veggie.",
    rarity: "common",
    value: 0.25,
    dateAdded: "2024-07-18",
    status: "live",
  },
];
